import './configOverrides';
import { GameMode } from './modules/gameMode/gameMode';
import { GameUI } from './modules/gameUI/gameUI';
import { PlayerManager } from './modules/player/playerManager';
import { TeamManager } from './modules/team/teamManager';
import { Scoreboard } from './modules/scoreboard/scoreboard';
import { CapturePointManager } from './modules/capturePoint/capturePointManager';
import { GameUIManager } from './modules/gameUI/gameUIManager';
import { ScoreboardManager } from './modules/scoreboard/scoreboardManager';
import { RestrictedAreaManager } from './modules/restrictedArea/restrictedAreaManager';
import { debug } from './debugTool/adminDebugTool';

const gameUI = GameUI.getInstance();
const playerManager = PlayerManager.getInstance();
const teamManager = TeamManager.getInstance();
const capturePointManager = CapturePointManager.getInstance();
GameMode.GetInstance(playerManager, teamManager);
const restrictedAreas = RestrictedAreaManager.getInstance(playerManager);
GameUIManager.getInstance(gameUI, teamManager, capturePointManager, restrictedAreas);
const scoreboard = Scoreboard.getInstance();
ScoreboardManager.getInstance(scoreboard, playerManager);
